# Generated by Django 5.2.6 on 2025-09-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(null=True, upload_to="documents/"),
        ),
    ]
