# Generated by Django 5.2.6 on 2025-09-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_note",
            field=models.TextField(max_length=50, null=True),
        ),
    ]
