# Generated by Django 5.2.6 on 2025-09-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_course_course_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_note",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_note",
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
