# Generated by Django 5.2.6 on 2025-09-14 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_course_course_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
