# Generated by Django 5.2.6 on 2025-09-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_course_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
