# Generated by Django 5.2.6 on 2025-09-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_document_user_flashcard_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
