# Generated by Django 5.2.6 on 2025-09-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_note",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_note",
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="answer",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="question",
            field=models.TextField(max_length=1000),
        ),
    ]
