import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { CoursesContextProvider } from "@/contexts/DataContext";
import { ReactQueryProvider } from "@/contexts/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <CoursesContextProvider>
            <Navbar />
            {children}
          </CoursesContextProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
